Update Dockerfile
I've to made this change to make it working. Otherwise I was getting the following exception (as it was trying to use CMD as shell):

'Invoke-WebRequest' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Service 'dotnetsdk' failed to build : The command 'cmd /S /C Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"' returned a non-zero code: 1

Same issue will happen with the RUN $path command.